name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Установить зависимости
        run: npm install
      - name: Дать разрешения
        run: chmod +x ./node_modules/.bin/jest
      - name: Запустить тесты
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: website-files
          path: .
      - name: Загрузить на gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          user_name: ${{ secrets.GIT_NAME }}
          repo_name: 'korolevalexander34.github.io'
          publish_branch: gh-pages
          user_email: ${{ secrets.GIT_EMAIL }}
          
          

